[package]
name = "bindgen_macro"
version = "0.1.0"
authors = ["Miguel \"Peppermint\" Robledo <migroble@ucm.es>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "parsing"] }
quote = "1.0"
